language: php

php:
  - 5.6
  - 7.0
  - 7.2
  - 7.3
  - nightly

before_script:
  - pear install pear/PHP_CodeSniffer
  - composer install -n
  - phpenv rehash
  - wget https://scrutinizer-ci.com/ocular.phar

script:
  - vendor/bin/phpunit -c Tests/ --coverage-clover=coverage.clover
  - phpcs --standard=PSR2 --extensions=php --ignore=vendor .
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
