<?php

namespace Jb\Bundle\PhumborBundle\Repository;

/**
 * PhumborAssetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhumborAssetRepository extends \Doctrine\ORM\EntityRepository
{
}
